"""add sprite column

Revision ID: d8ec6aa6b22f
Revises: 78fb234eef44
Create Date: 2026-05-18 14:04:40.488997

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd8ec6aa6b22f'
down_revision = '78fb234eef44'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('creatures', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sprite', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('creatures', schema=None) as batch_op:
        batch_op.drop_column('sprite')

    # ### end Alembic commands ###
